pipeline:
  name: mytriggerpipelinefromcode
  identifier: mytriggerpipelinefromcode
  projectIdentifier: labsproject
  orgIdentifier: abhilabs
  tags: {}
  stages:
    - stage:
        name: hello
        identifier: hello
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo <+ var identityFunction = function(keyNameInput) {
                               return keyNameInput.startsWith("key") ? <+trigger.branch> : "main";
                          }
                             var keyName = <+trigger.branch>; // or another string
                             identityFunction(keyName);
                          >
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
