pipeline:
  name: mytriggerpipelinefromcode
  identifier: mytriggerpipelinefromcode
  projectIdentifier: labsproject
  orgIdentifier: abhilabs
  tags: {}
  stages:
    - stage:
        name: hello
        identifier: hello
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo newtest3
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
